server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/michelsantos10/poc-config-server
  security:
    user:
      name: michel
      password: michel